parser: "@typescript-eslint/parser"

plugins:
  - "@typescript-eslint"

parserOptions:
  ecmaFeatures:
    jsx: true
    ecmaVersion: 2018
    sourceType: module

env:
  browser: true
  es6: true
  node: true
  jest: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:jest/recommended
  - plugin:prettier/recommended

settings:
  react:
    version: 16.4.2

rules:
  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: "^_"
      varsIgnorePattern: "^_"
  "@typescript-eslint/no-empty-function":
    - off
  no-var:
    - off
  no-console:
    - off
  react/prop-types:
    - off
  react/no-find-dom-node:
    - off
  no-debugger:
    - off
  prefer-const:
    - off
  "@typescript-eslint/no-explicit-any":
    - off
  "@typescript-eslint/ban-ts-comment":
    - off
  "@typescript-eslint/explicit-module-boundary-types":
    - off
  "@typescript-eslint/no-var-requires":
    - off
  "@typescript-eslint/ban-types":
    - off
