name: Brim Windows release artifacts promote to tagged

on:
  push:
    tags:
      - v*

jobs:
  promote:
    runs-on: windows-2019
    steps:
    - name: Extract tag name
      run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"
      id: extract_tag
      shell: bash
    - name: Copy artifacts from Google Cloud Storage bucket to GitHub Release page
      env:
        CLOUDSDK_PYTHON: ${{ env.pythonLocation }}\python.exe
      run: gsutil cp -r gs://${{ secrets.GCLOUD_BUCKET_RELEASES }}/brim/windows/rc-${{ steps.extract_tag.outputs.tag }} .
    - name: Upload release candidate artifacts to GitHub Releases
      uses: svenstaro/upload-release-action@1.1.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: rc-${{ steps.extract_tag.outputs.tag }}\*
        file_glob: true
        overwrite: true
